version: "3.7"
services: 
    web:
        env_file: 
            - "./.env.prod"
        environment: 
            - RUBY_ENV=production
        command: "bundle exec rackup -E production --host 0.0.0.0 -p 4567"